'use strict';
/* scenes.js */
const CW=560,CH=220,P=4;
function _lbl(ctx,t,c,y){ctx.fillStyle=c||'#ffffff';ctx.font='6px "Press Start 2P",monospace';ctx.textAlign='center';ctx.fillText(t,CW/2,y||15);ctx.textAlign='left';}
function _fig(ctx,x,y,hc,bc,pc,r){const S=document.documentElement.getAttribute('data-theme')==='stars';ctx.fillStyle=hc;if(S&&r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x+P,y,P*3,P*3,2);else ctx.rect(x+P,y,P*3,P*3);ctx.fill();}else ctx.fillRect(x+P,y,P*3,P*3);ctx.fillStyle=bc;ctx.fillRect(x,y+P*3,P*5,P*4);ctx.fillStyle=pc;ctx.fillRect(x,y+P*7,P*2,P*4);ctx.fillRect(x+P*3,y+P*7,P*2,P*4);}
class BS{constructor(id){this.canvas=document.getElementById(id);this.ctx=this.canvas?this.canvas.getContext('2d'):null;this.raf=null;this.t=0;}stop(){if(this.raf){cancelAnimationFrame(this.raf);this.raf=null;}}}
const VD_s1={ref:'Al-Masad 111:1',arabic:'تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ',english:'"May Abu Lahab\'s hands perish!" (111:1)',note:"The Prophet's uncle — fiercest enemy. Predicted: never Muslim."};
const VD_s2={ref:'Al-Masad 111:2',arabic:'مَا أَغْنَىٰ عَنْهُ مَالُهُ وَمَا كَسَبَ',english:'"His wealth availed him nothing." (111:2)',note:"All wealth and status: useless. Allah's decree prevails."};
const VD_s3={ref:'Al-Masad 111:4-5',arabic:'فِي جِيدِهَا حَبْلٌ مِّن مَّسَدٍ',english:'"Around her neck a rope of palm fiber." (111:5)',note:"His wife: wood-carrier on Prophet's path. In Hell: palm rope."};
class S1 extends BS{constructor(){super('canvas-1');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s1);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#1a0404';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#381010';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('🔥',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#f07030';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('تَبَّتْ يَدَا أَبِي لَهَبٍ و',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"May Abu Lahab\'s hands perish!" (111:1)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Abu Lahab Condemned — 111:1','#fff0e8');};draw();}}
class S2 extends BS{constructor(){super('canvas-2');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s2);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#1a0404';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#381010';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('💀',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#f07030';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('مَا أَغْنَىٰ عَنْهُ مَالُهُ ',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"His wealth availed him nothing." (111:2)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Wealth Useless — 111:2','#fff0e8');};draw();}}
class S3 extends BS{constructor(){super('canvas-3');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s3);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#1a0404';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#381010';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('🌿',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#f07030';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('فِي جِيدِهَا حَبْلٌ مِّن مَّ',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"Around her neck a rope of palm fiber." (111:5)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,"CLICK: His Wife's Punishment — 111:4-5",'#fff0e8');};draw();}}
const scenes={};
function initScenes(){scenes[1]=new S1();scenes[2]=new S2();scenes[3]=new S3();}
function startScene(n){if(scenes[n])scenes[n].start();}
function stopAllScenes(){Object.values(scenes).forEach(s=>s.stop());}
