'use strict';
/* scenes.js */
const CW=560,CH=220,P=4;
function _lbl(ctx,t,c,y){ctx.fillStyle=c||'#ffffff';ctx.font='6px "Press Start 2P",monospace';ctx.textAlign='center';ctx.fillText(t,CW/2,y||15);ctx.textAlign='left';}
function _fig(ctx,x,y,hc,bc,pc,r){const S=document.documentElement.getAttribute('data-theme')==='stars';ctx.fillStyle=hc;if(S&&r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x+P,y,P*3,P*3,2);else ctx.rect(x+P,y,P*3,P*3);ctx.fill();}else ctx.fillRect(x+P,y,P*3,P*3);ctx.fillStyle=bc;ctx.fillRect(x,y+P*3,P*5,P*4);ctx.fillStyle=pc;ctx.fillRect(x,y+P*7,P*2,P*4);ctx.fillRect(x+P*3,y+P*7,P*2,P*4);}
class BS{constructor(id){this.canvas=document.getElementById(id);this.ctx=this.canvas?this.canvas.getContext('2d'):null;this.raf=null;this.t=0;}stop(){if(this.raf){cancelAnimationFrame(this.raf);this.raf=null;}}}
const VD_s1={ref:'An-Nas 114:1-3',arabic:'قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۩ مَلِكِ النَّاسِ ۩ إِلَٰهِ النَّاسِ',english:'"Lord, King, God of Mankind." (114:1-3)',note:'Three titles of divine authority over all humanity.'};
const VD_s2={ref:'An-Nas 114:4-5',arabic:'مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ',english:'"The whisperer who withdraws." (114:4)',note:'Shaytan whispers when you forget, retreats when you remember.'};
const VD_s3={ref:'An-Nas 114:6',arabic:'مِنَ الْجِنَّةِ وَالنَّاسِ',english:'"From jinn and men." (114:6)',note:'Evil from both. Dhikr is your shield. Final surah!'};
class S1 extends BS{constructor(){super('canvas-1');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s1);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#100820';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#281848';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('🌍',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#d0a0f8';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('قُلْ أَعُوذُ بِرَبِّ النَّاس',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"Lord, King, God of Mankind." (114:1-3)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Three Titles — 114:1-3','#f8f0ff');};draw();}}
class S2 extends BS{constructor(){super('canvas-2');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s2);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#100820';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#281848';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('😈',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#d0a0f8';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('مِن شَرِّ الْوَسْوَاسِ الْخَ',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"The whisperer who withdraws." (114:4)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: The Whisperer — 114:4-5','#f8f0ff');};draw();}}
class S3 extends BS{constructor(){super('canvas-3');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s3);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#100820';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#281848';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('🛡️',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#d0a0f8';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('مِنَ الْجِنَّةِ وَالنَّاسِ',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"From jinn and men." (114:6)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Juz Amma Complete! — 114:6','#f8f0ff');};draw();}}
const scenes={};
function initScenes(){scenes[1]=new S1();scenes[2]=new S2();scenes[3]=new S3();}
function startScene(n){if(scenes[n])scenes[n].start();}
function stopAllScenes(){Object.values(scenes).forEach(s=>s.stop());}
