'use strict';
/* Surah Al-Jinn (72) — The Jinn */
window.STORAGE_KEY = 'jinnQuestSave';
window.state = {
  explorerName:'', xp:0, gems:0, completed:[],
  s1Checked:false,
  s2Answers:{}, s2Checked:false,
  s3Checked:false,
  s4Answers:{}, s4Checked:false,
  s5Checked:false,
};

const REWARDS = {
  1:{xp:75, gems:3, icon:'👁️', title:'Jinn Heard the Quran!', msg:"SubhanAllah! A group of jinn — unseen beings — heard the Quran being recited by the Prophet ﷺ. And they believed! 'Inna sami'na Quranan 'ajaba — we have heard a wondrous Quran!' Even the jinn recognized the truth. How remarkable that the Book of Allah moves hearts across the unseen world!"},
  2:{xp:80, gems:3, icon:'🌌', title:'Jinn Report Back',      msg:"MashAllah! The jinn went back to their people and reported: 'We heard amazing Quran — guides to truth!' They warned against shirk, affirmed Allah has no wife or child, confessed their old mistakes of spying on heaven, and accepted Islam. Amazing da'wah from the jinn themselves!"},
  3:{xp:85, gems:3, icon:'🛡️', title:'Only Allah Guides',    msg:"Allahu Akbar! The message: 'Whoever believes and does right has no fear of wrong.' The mosques are for Allah alone. When the Prophet ﷺ stands to call on Allah, they almost rush over him in crowds — such is the power of the Quran! And guidance is ONLY from Allah."},
  4:{xp:100, gems:4, icon:'✨', title:'Al-Jinn Complete!',    msg:"ALLAHUMMA BARIK! Al-Jinn complete! The unseen world believes. The Quran moves jinn and humans alike. 'Wa an al-masajida lillahi fala tad'u ma'a Allahi ahada' — the mosques are for Allah alone, so call on no one beside Him. May we call on Allah alone! Ameen!"},
  5:{xp:80, gems:3, icon:'📖', title:'BONUS COMPLETE!', msg:'MashAllah! You mastered the Arabic words of Surah Al-Jinn word by word!'},
};

window.SURAH_CONFIG = {
  id:'s72', surahName:'Al-Jinn', surahArabic:'الجن', totalLevels:5, wbwSection:5, rewards:REWARDS,
  tileIcons:['👁️','🌌','🛡️','✨'],
  tileLabels:['Jinn Believe','Their Report','Straight Path','Jinn Complete'],
  welcomeMsg:{
    fresh:   name=>`As-salamu alaykum, ${name}! Al-Jinn — A group of jinn heard the Quran and immediately believed! They went back to warn their people. 4 levels exploring the unseen world's testimony to the Quran!`,
    partial: (name,done)=>`Welcome back, ${name}! ${done}/4 levels done. Even the jinn are on the straight path! 👁️`,
    complete: name=>`MashAllah, ${name}! Al-Jinn complete! May we believe like those jinn! 🏆`,
  },
};

const S1_QUIZ = [
  {q:'What does "inna sami\'na Quranan \'ajaban" (72:1) mean?',
   opts:['We have seen a wondrous prophet among them','We have heard a wondrous and amazing Quran','We have found a wonderful new way of life','We have learned a beautiful and astonishing language'],
   correct:1},
  {q:'What did the jinn say they believed the Quran would guide them to (72:2)?',
   opts:['To prosperity and riches in this world','To right conduct — so they believed in it','To peace among the jinn and human people','To wisdom and knowledge they had never known'],
   correct:1},
  {q:'What did the jinn declare about Allah having a partner (72:3)?',
   opts:['They said Allah has partners who assist Him','He has taken no wife and no son — exalted is He','They believed Allah shares power with the jinn','They thought the angels were Allah\'s children'],
   correct:1},
  {q:'What does 72:6 say some men used to do with the jinn?',
   opts:['Made agreements with jinn for protection','Some men sought refuge with jinn and increased in sin','Used jinn magic to harm their enemies always','Traded knowledge with jinn for worldly power'],
   correct:1},
];

const S2_ITEMS = [
  {id:'j1', text:'إِنَّا سَمِعْنَا قُرْآنًا\nعَجَبًا فَآمَنَّا بِهِ',  zone:'z1'},
  {id:'j2', text:'مَا اتَّخَذَ صَاحِبَةً\nوَلَا وَلَدًا',              zone:'z2'},
  {id:'j3', text:'كُنَّا نَقْعُدُ مِنْهَا\nمَقَاعِدَ لِلسَّمْعِ',      zone:'z3'},
  {id:'j4', text:'مُلِئَتْ حَرَسًا شَدِيدًا\nوَشُهُبًا',               zone:'z4'},
];
const S2_ZONES = [
  {id:'z1', desc:'The jinn heard the Quran and believed — they went back to warn their people (72:1-2)'},
  {id:'z2', desc:'Our Lord is exalted — He has taken no wife or son (72:3)'},
  {id:'z3', desc:'We used to sit in positions of the sky to listen in on the heavens (72:9)'},
  {id:'z4', desc:'But now we find it filled with fierce guards and burning flames (72:8)'},
];

const S3_QUIZ = [
  {q:'What does "wa an al-masajida lillahi fala tad\'u ma\'a Allahi ahadan" (72:18) mean?',
   opts:['The jinn are forbidden from entering mosques','The mosques belong to Allah — call on no one beside Him','The Prophet ﷺ should pray in every place on earth','The believers should build mosques in every nation'],
   correct:1},
  {q:'What happened when the Prophet ﷺ stood to invoke Allah according to 72:19?',
   opts:['The jinn attacked him with burning flames','The jinn almost crowded over him in multitudes','The jinn flew away afraid of the Quran\'s power','The jinn went silent and listened in deep reverence'],
   correct:1},
  {q:'What does 72:13 say about fear when one believes in the straight way?',
   opts:['Whoever believes has no fear of wrong or injustice','Those who believe will be protected from the jinn','Belief removes fear of death and the hereafter','The believer is protected from every evil attack'],
   correct:0},
  {q:'Who knows the unseen (ghayb) according to 72:26?',
   opts:['The senior jinn who guard the heavens above','Only Allah — He discloses none except to chosen messengers','The prophets and the angels who serve Allah','Those who are pure of heart and deep in worship'],
   correct:1},
];

const S4_FIB = [
  {verse:'إِنَّا سَمِعْنَا قُرْآنًا _____', opts:['عَجَبًا','كَرِيمًا','عَظِيمًا','مُبِينًا'], correct:0, ref:'72:1', translation:'Indeed, we have heard a wondrous Quran'},
  {verse:'مَا اتَّخَذَ صَاحِبَةً وَلَا _____', opts:['وَلَدًا','شَرِيكًا','وَزِيرًا','نَظِيرًا'], correct:0, ref:'72:3', translation:'He has not taken a wife or a son'},
  {verse:'فَوَجَدْنَاهَا مُلِئَتْ حَرَسًا شَدِيدًا وَ_____', opts:['شُهُبًا','نَارًا','حِجَارَةً','رِيَاحًا'], correct:0, ref:'72:8', translation:'We found it filled with fierce guards and burning flames'},
  {verse:'وَأَنَّ الْمَسَاجِدَ _____ فَلَا تَدْعُوا مَعَ اللَّهِ أَحَدًا', opts:['لِلَّهِ','لِلنَّاسِ','لِلْعِبَادِ','لِلْمُؤْمِنِينَ'], correct:0, ref:'72:18', translation:'The mosques are for Allah, so do not invoke with Allah anyone'},
  {verse:'عَالِمُ _____ فَلَا يُظْهِرُ عَلَىٰ غَيْبِهِ أَحَدًا', opts:['الْغَيْبِ','الْأَمْرِ','السِّرِّ','الْعِلْمِ'], correct:0, ref:'72:26', translation:'Knower of the unseen, He does not reveal His unseen to anyone'},
];

function renderSection1Game(){renderQuiz(1,S1_QUIZ);}
function checkSection1(){checkQuiz(1,S1_QUIZ);}
function renderSection2Game(){renderDragDrop(2,S2_ITEMS,S2_ZONES);}
function checkSection2(){checkDragDrop(2,S2_ZONES);}
function renderSection3Game(){renderQuiz(3,S3_QUIZ);}
function checkSection3(){checkQuiz(3,S3_QUIZ);}
function renderSection4Game(){renderFillBlank(4,S4_FIB);}
function checkSection4(){checkFillBlank(4,S4_FIB);}
function updateUIExtra(){window._drawBuildCanvas(window.state.completed.length);}

window._drawBuildCanvas = function(n) {
  const cv=document.getElementById('build-canvas');if(!cv)return;
  const ctx=cv.getContext('2d'),W=cv.width,H=cv.height;
  const st=document.documentElement.getAttribute('data-theme')==='stars';
  const sky=st?'#0c0418':'#060210', acc=st?'#40e090':'#30c070';
  ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);
  // Stars/mystery
  if(n>=1){for(let i=0;i<40;i++){const r=Math.random();ctx.fillStyle=`rgba(${r>0.5?'100,220,180':'180,100,255'},${0.4+Math.random()*0.5})`;ctx.beginPath();ctx.arc(Math.random()*W,Math.random()*H*0.7,1.5,0,Math.PI*2);ctx.fill();}}
  // Jinn figures
  if(n>=2){for(let i=0;i<4;i++){ctx.fillStyle=`rgba(112,48,176,${0.5+i*0.1})`;ctx.beginPath();ctx.arc(W*0.15+i*W*0.22,H*0.55,10,0,Math.PI*2);ctx.fill();ctx.fillRect(W*0.15+i*W*0.22-5,H*0.55+10,10,14);}}
  // Mosque silhouette
  if(n>=3){ctx.fillStyle='rgba(64,224,144,0.3)';ctx.fillRect(W*0.4,H*0.35,W*0.2,H*0.3);ctx.beginPath();ctx.arc(W*0.5,H*0.35,W*0.07,0,Math.PI,true);ctx.fill();}
  ctx.fillStyle=acc;ctx.font='6px "Press Start 2P",monospace';ctx.textAlign='center';
  ctx.fillText(n>=4?'AL-JINN COMPLETE 👁️':`Al-Jinn — ${n}/4 levels`,W/2,12);ctx.textAlign='left';
};

const WBW_DATA = [
  {label:'72:1 — قُلْ أُوحِيَ إِلَيَّ أَنَّهُ اسْتَمَعَ نَفَرٌ مِّنَ الْجِنِّ فَقَالُوا إِنَّا سَمِعْنَا قُرْآنًا عَجَبًا', words:[
    {ar:'قُلْ', tr:'qul', en:'Say', freq:332},
    {ar:'أُوحِيَ', tr:'ūḥiya', en:'it has been revealed', freq:12},
    {ar:'إِلَيَّ', tr:'ilayya', en:'to me', freq:26},
    {ar:'أَنَّهُ', tr:'annahu', en:'that', freq:76},
    {ar:'اسْتَمَعَ', tr:'istamaʿa', en:'listened', freq:3},
    {ar:'نَفَرٌ', tr:'nafarun', en:'a group', freq:4},
    {ar:'مِّنَ', tr:'mina', en:'of', freq:3000},
    {ar:'الْجِنِّ', tr:'al-jinni', en:'the jinn', freq:10},
    {ar:'فَقَالُوا', tr:'fa-qālū', en:'and they said', freq:92},
    {ar:'إِنَّا', tr:'innā', en:'indeed we', freq:132},
    {ar:'سَمِعْنَا', tr:'samiʿnā', en:'have heard', freq:9},
    {ar:'قُرْآنًا', tr:'qurʾānan', en:'a Quran', freq:6},
    {ar:'عَجَبًا', tr:'ʿajaban', en:'wondrous', freq:2},
  ]},
  {label:'72:2 — يَهْدِي إِلَى الرُّشْدِ فَآمَنَّا بِهِ وَلَن نُّشْرِكَ بِرَبِّنَا أَحَدًا', words:[
    {ar:'يَهْدِي', tr:'yahdī', en:'It guides', freq:18},
    {ar:'إِلَى', tr:'ilā', en:'to', freq:700},
    {ar:'الرُّشْدِ', tr:'ar-rushdi', en:'right guidance', freq:3},
    {ar:'فَآمَنَّا', tr:'fa-āmannā', en:'so we believed', freq:5},
    {ar:'بِهِ', tr:'bihī', en:'in it', freq:110},
    {ar:'وَلَن', tr:'wa-lan', en:'and never', freq:40},
    {ar:'نُّشْرِكَ', tr:'nushrika', en:'will we associate', freq:3},
    {ar:'بِرَبِّنَا', tr:'bi-Rabbinā', en:'with our Lord', freq:8},
    {ar:'أَحَدًا', tr:'aḥadan', en:'anyone', freq:18},
  ]},
  {label:'72:3 — وَأَنَّهُ تَعَالَىٰ جَدُّ رَبِّنَا مَا اتَّخَذَ صَاحِبَةً وَلَا وَلَدًا', words:[
    {ar:'وَأَنَّهُ', tr:'wa-annahu', en:'And that', freq:76},
    {ar:'تَعَالَىٰ', tr:'taʿālā', en:'exalted is', freq:6},
    {ar:'جَدُّ', tr:'jaddu', en:'the majesty', freq:1},
    {ar:'رَبِّنَا', tr:'Rabbinā', en:'of our Lord', freq:30},
    {ar:'مَا', tr:'mā', en:'not', freq:2000},
    {ar:'اتَّخَذَ', tr:'ittakhadha', en:'has He taken', freq:14},
    {ar:'صَاحِبَةً', tr:'ṣāḥibatan', en:'a wife', freq:3},
    {ar:'وَلَا', tr:'wa-lā', en:'and not', freq:400},
    {ar:'وَلَدًا', tr:'waladan', en:'a son', freq:8},
  ]},
  {label:'72:4 — وَأَنَّهُ كَانَ يَقُولُ سَفِيهُنَا عَلَى اللَّهِ شَطَطًا', words:[
    {ar:'وَأَنَّهُ', tr:'wa-annahu', en:'And that', freq:76},
    {ar:'كَانَ', tr:'kāna', en:'used to', freq:359},
    {ar:'يَقُولُ', tr:'yaqūlu', en:'say', freq:71},
    {ar:'سَفِيهُنَا', tr:'safīhunā', en:'the foolish among us', freq:1},
    {ar:'عَلَى', tr:'ʿalā', en:'about', freq:820},
    {ar:'اللَّهِ', tr:'Allāhi', en:'Allah', freq:2699},
    {ar:'شَطَطًا', tr:'shaṭaṭan', en:'an excessive lie', freq:2},
  ]},
  {label:'72:5 — وَأَنَّا ظَنَنَّا أَن لَّن تَقُولَ الْإِنسُ وَالْجِنُّ عَلَى اللَّهِ كَذِبًا', words:[
    {ar:'وَأَنَّا', tr:'wa-annā', en:'And we had thought', freq:132},
    {ar:'ظَنَنَّا', tr:'ẓanannā', en:'we assumed', freq:3},
    {ar:'أَن', tr:'an', en:'that', freq:560},
    {ar:'لَّن', tr:'lan', en:'never', freq:40},
    {ar:'تَقُولَ', tr:'taqūla', en:'would say', freq:71},
    {ar:'الْإِنسُ', tr:'al-insu', en:'mankind', freq:7},
    {ar:'وَالْجِنُّ', tr:'wal-jinnu', en:'and the jinn', freq:10},
    {ar:'عَلَى', tr:'ʿalā', en:'about', freq:820},
    {ar:'اللَّهِ', tr:'Allāhi', en:'Allah', freq:2699},
    {ar:'كَذِبًا', tr:'kadhiban', en:'a lie', freq:6},
  ]},
  {label:'72:6 — وَأَنَّهُ كَانَ رِجَالٌ مِّنَ الْإِنسِ يَعُوذُونَ بِرِجَالٍ مِّنَ الْجِنِّ فَزَادُوهُمْ رَهَقًا', words:[
    {ar:'وَأَنَّهُ', tr:'wa-annahu', en:'And that', freq:76},
    {ar:'كَانَ', tr:'kāna', en:'there were', freq:359},
    {ar:'رِجَالٌ', tr:'rijālun', en:'men', freq:15},
    {ar:'مِّنَ', tr:'mina', en:'from', freq:3000},
    {ar:'الْإِنسِ', tr:'al-insi', en:'mankind', freq:7},
    {ar:'يَعُوذُونَ', tr:'yaʿūdhūna', en:'who sought refuge', freq:1},
    {ar:'بِرِجَالٍ', tr:'bi-rijālin', en:'with men', freq:15},
    {ar:'مِّنَ', tr:'mina', en:'from', freq:3000},
    {ar:'الْجِنِّ', tr:'al-jinni', en:'the jinn', freq:10},
    {ar:'فَزَادُوهُمْ', tr:'fa-zādūhum', en:'so they increased them', freq:2},
    {ar:'رَهَقًا', tr:'rahaqan', en:'in burden', freq:2},
  ]},
  {label:'72:7 — وَأَنَّهُمْ ظَنُّوا كَمَا ظَنَنتُمْ أَن لَّن يَبْعَثَ اللَّهُ أَحَدًا', words:[
    {ar:'وَأَنَّهُمْ', tr:'wa-annahum', en:'And they thought', freq:35},
    {ar:'ظَنُّوا', tr:'ẓannū', en:'assumed', freq:4},
    {ar:'كَمَا', tr:'kamā', en:'just as', freq:82},
    {ar:'ظَنَنتُمْ', tr:'ẓanantum', en:'you assumed', freq:3},
    {ar:'أَن', tr:'an', en:'that', freq:560},
    {ar:'لَّن', tr:'lan', en:'never', freq:40},
    {ar:'يَبْعَثَ', tr:'yabʿatha', en:'would raise', freq:10},
    {ar:'اللَّهُ', tr:'Allāhu', en:'Allah', freq:2699},
    {ar:'أَحَدًا', tr:'aḥadan', en:'anyone', freq:18},
  ]},
  {label:'72:8 — وَأَنَّا لَمَسْنَا السَّمَاءَ فَوَجَدْنَاهَا مُلِئَتْ حَرَسًا شَدِيدًا وَشُهُبًا', words:[
    {ar:'وَأَنَّا', tr:'wa-annā', en:'And we', freq:132},
    {ar:'لَمَسْنَا', tr:'lamasnā', en:'touched', freq:1},
    {ar:'السَّمَاءَ', tr:'as-samāʾa', en:'the heaven', freq:120},
    {ar:'فَوَجَدْنَاهَا', tr:'fa-wajadnāhā', en:'and found it', freq:2},
    {ar:'مُلِئَتْ', tr:'muliʾat', en:'filled with', freq:1},
    {ar:'حَرَسًا', tr:'ḥarasan', en:'guards', freq:1},
    {ar:'شَدِيدًا', tr:'shadīdan', en:'fierce', freq:20},
    {ar:'وَشُهُبًا', tr:'wa-shuhuban', en:'and burning flames', freq:1},
  ]},
  {label:'72:9 — وَأَنَّا كُنَّا نَقْعُدُ مِنْهَا مَقَاعِدَ لِلسَّمْعِ فَمَن يَسْتَمِعِ الْآنَ يَجِدْ لَهُ شِهَابًا رَّصَدًا', words:[
    {ar:'وَأَنَّا', tr:'wa-annā', en:'And we', freq:132},
    {ar:'كُنَّا', tr:'kunnā', en:'used to', freq:65},
    {ar:'نَقْعُدُ', tr:'naqʿudu', en:'sit', freq:2},
    {ar:'مِنْهَا', tr:'minhā', en:'therein', freq:40},
    {ar:'مَقَاعِدَ', tr:'maqāʿida', en:'in positions', freq:2},
    {ar:'لِلسَّمْعِ', tr:'lis-samʿi', en:'for listening', freq:2},
    {ar:'فَمَن', tr:'fa-man', en:'but whoever', freq:540},
    {ar:'يَسْتَمِعِ', tr:'yastamiʿi', en:'listens', freq:3},
    {ar:'الْآنَ', tr:'al-āna', en:'now', freq:8},
    {ar:'يَجِدْ', tr:'yajid', en:'will find', freq:16},
    {ar:'لَهُ', tr:'lahu', en:'for him', freq:220},
    {ar:'شِهَابًا', tr:'shihāban', en:'a burning flame', freq:2},
    {ar:'رَّصَدًا', tr:'raṣadan', en:'lying in wait', freq:2},
  ]},
  {label:'72:10 — وَأَنَّا لَا نَدْرِي أَشَرٌّ أُرِيدَ بِمَن فِي الْأَرْضِ أَمْ أَرَادَ بِهِمْ رَبُّهُمْ رَشَدًا', words:[
    {ar:'وَأَنَّا', tr:'wa-annā', en:'And we', freq:132},
    {ar:'لَا', tr:'lā', en:'do not', freq:1738},
    {ar:'نَدْرِي', tr:'nadrī', en:'know', freq:2},
    {ar:'أَشَرٌّ', tr:'a-sharrun', en:'whether evil', freq:4},
    {ar:'أُرِيدَ', tr:'urīda', en:'is intended', freq:8},
    {ar:'بِمَن', tr:'bi-man', en:'for those', freq:540},
    {ar:'فِي', tr:'fī', en:'on', freq:1700},
    {ar:'الْأَرْضِ', tr:'al-arḍi', en:'the earth', freq:280},
    {ar:'أَمْ', tr:'am', en:'or', freq:120},
    {ar:'أَرَادَ', tr:'arāda', en:'intends', freq:20},
    {ar:'بِهِمْ', tr:'bihim', en:'for them', freq:28},
    {ar:'رَبُّهُمْ', tr:'Rabbuhum', en:'their Lord', freq:36},
    {ar:'رَشَدًا', tr:'rashadan', en:'right guidance', freq:3},
  ]},
  {label:'72:11 — وَأَنَّا مِنَّا الصَّالِحُونَ وَمِنَّا دُونَ ذَٰلِكَ كُنَّا طَرَائِقَ قِدَدًا', words:[
    {ar:'وَأَنَّا', tr:'wa-annā', en:'And among us', freq:132},
    {ar:'مِنَّا', tr:'minnā', en:'of us', freq:14},
    {ar:'الصَّالِحُونَ', tr:'aṣ-ṣāliḥūna', en:'are the righteous', freq:8},
    {ar:'وَمِنَّا', tr:'wa-minnā', en:'and among us', freq:14},
    {ar:'دُونَ', tr:'dūna', en:'other than', freq:73},
    {ar:'ذَٰلِكَ', tr:'dhālika', en:'that', freq:700},
    {ar:'كُنَّا', tr:'kunnā', en:'we have been', freq:65},
    {ar:'طَرَائِقَ', tr:'ṭarāʾiqa', en:'of differing ways', freq:2},
    {ar:'قِدَدًا', tr:'qidadan', en:'factions', freq:1},
  ]},
  {label:'72:12 — وَأَنَّا ظَنَنَّا أَن لَّن نُّعْجِزَ اللَّهَ فِي الْأَرْضِ وَلَن نُّعْجِزَهُ هَرَبًا', words:[
    {ar:'وَأَنَّا', tr:'wa-annā', en:'And we know', freq:132},
    {ar:'ظَنَنَّا', tr:'ẓanannā', en:'that', freq:3},
    {ar:'أَن', tr:'an', en:'that', freq:560},
    {ar:'لَّن', tr:'lan', en:'never', freq:40},
    {ar:'نُّعْجِزَ', tr:'nuʿjiza', en:'can we escape', freq:3},
    {ar:'اللَّهَ', tr:'Allāha', en:'Allah', freq:2699},
    {ar:'فِي', tr:'fī', en:'upon', freq:1700},
    {ar:'الْأَرْضِ', tr:'al-arḍi', en:'the earth', freq:280},
    {ar:'وَلَن', tr:'wa-lan', en:'and never', freq:40},
    {ar:'نُّعْجِزَهُ', tr:'nuʿjizahu', en:'can we escape Him', freq:1},
    {ar:'هَرَبًا', tr:'haraban', en:'by flight', freq:1},
  ]},
  {label:'72:13 — وَأَنَّا لَمَّا سَمِعْنَا الْهُدَىٰ آمَنَّا بِهِ فَمَن يُؤْمِن بِرَبِّهِ فَلَا يَخَافُ بَخْسًا وَلَا رَهَقًا', words:[
    {ar:'وَأَنَّا', tr:'wa-annā', en:'And when', freq:132},
    {ar:'لَمَّا', tr:'lammā', en:'when', freq:50},
    {ar:'سَمِعْنَا', tr:'samiʿnā', en:'we heard', freq:9},
    {ar:'الْهُدَىٰ', tr:'al-hudā', en:'the guidance', freq:50},
    {ar:'آمَنَّا', tr:'āmannā', en:'we believed', freq:14},
    {ar:'بِهِ', tr:'bihī', en:'in it', freq:110},
    {ar:'فَمَن', tr:'fa-man', en:'so whoever', freq:540},
    {ar:'يُؤْمِن', tr:'yuʾmin', en:'believes', freq:50},
    {ar:'بِرَبِّهِ', tr:'bi-Rabbihī', en:'in his Lord', freq:12},
    {ar:'فَلَا', tr:'fa-lā', en:'then no', freq:100},
    {ar:'يَخَافُ', tr:'yakhāfu', en:'he will fear', freq:8},
    {ar:'بَخْسًا', tr:'bakhsan', en:'loss', freq:2},
    {ar:'وَلَا', tr:'wa-lā', en:'nor', freq:400},
    {ar:'رَهَقًا', tr:'rahaqan', en:'burden', freq:2},
  ]},
  {label:'72:14 — وَأَنَّا مِنَّا الْمُسْلِمُونَ وَمِنَّا الْقَاسِطُونَ فَمَنْ أَسْلَمَ فَأُولَٰئِكَ تَحَرَّوْا رَشَدًا', words:[
    {ar:'وَأَنَّا', tr:'wa-annā', en:'And among us', freq:132},
    {ar:'مِنَّا', tr:'minnā', en:'of us', freq:14},
    {ar:'الْمُسْلِمُونَ', tr:'al-muslimūna', en:'are Muslims', freq:6},
    {ar:'وَمِنَّا', tr:'wa-minnā', en:'and among us', freq:14},
    {ar:'الْقَاسِطُونَ', tr:'al-qāsiṭūna', en:'are the unjust', freq:1},
    {ar:'فَمَنْ', tr:'fa-man', en:'so whoever', freq:540},
    {ar:'أَسْلَمَ', tr:'aslama', en:'accepted Islam', freq:6},
    {ar:'فَأُولَٰئِكَ', tr:'fa-ulāʾika', en:'those have', freq:40},
    {ar:'تَحَرَّوْا', tr:'taḥarraw', en:'sought out', freq:1},
    {ar:'رَشَدًا', tr:'rashadan', en:'right guidance', freq:3},
  ]},
  {label:'72:15 — وَأَمَّا الْقَاسِطُونَ فَكَانُوا لِجَهَنَّمَ حَطَبًا', words:[
    {ar:'وَأَمَّا', tr:'wa-ammā', en:'But as for', freq:28},
    {ar:'الْقَاسِطُونَ', tr:'al-qāsiṭūna', en:'the unjust', freq:1},
    {ar:'فَكَانُوا', tr:'fa-kānū', en:'they will be', freq:14},
    {ar:'لِجَهَنَّمَ', tr:'li-jahannama', en:'for Hell', freq:15},
    {ar:'حَطَبًا', tr:'ḥaṭaban', en:'firewood', freq:2},
  ]},
  {label:'72:16 — وَأَن لَّوِ اسْتَقَامُوا عَلَى الطَّرِيقَةِ لَأَسْقَيْنَاهُم مَّاءً غَدَقًا', words:[
    {ar:'وَأَن', tr:'wa-an', en:'And if', freq:560},
    {ar:'لَّوِ', tr:'lawi', en:'had', freq:112},
    {ar:'اسْتَقَامُوا', tr:'istaqāmū', en:'they stayed on', freq:2},
    {ar:'عَلَى', tr:'ʿalā', en:'upon', freq:820},
    {ar:'الطَّرِيقَةِ', tr:'aṭ-ṭarīqati', en:'the right way', freq:2},
    {ar:'لَأَسْقَيْنَاهُم', tr:'la-asqaynāhum', en:'We would have given them', freq:1},
    {ar:'مَّاءً', tr:'māʾan', en:'water', freq:42},
    {ar:'غَدَقًا', tr:'ghadaqan', en:'in abundance', freq:1},
  ]},
  {label:'72:17 — لِّنَفْتِنَهُمْ فِيهِ وَمَن يُعْرِضْ عَن ذِكْرِ رَبِّهِ يَسْلُكْهُ عَذَابًا صَعَدًا', words:[
    {ar:'لِّنَفْتِنَهُمْ', tr:'li-naftinahum', en:'to test them', freq:2},
    {ar:'فِيهِ', tr:'fīhi', en:'therein', freq:90},
    {ar:'وَمَن', tr:'wa-man', en:'and whoever', freq:540},
    {ar:'يُعْرِضْ', tr:'yuʿriḍ', en:'turns away', freq:7},
    {ar:'عَن', tr:'ʿan', en:'from', freq:320},
    {ar:'ذِكْرِ', tr:'dhikri', en:'the remembrance', freq:30},
    {ar:'رَبِّهِ', tr:'Rabbihī', en:'of his Lord', freq:36},
    {ar:'يَسْلُكْهُ', tr:'yaslukhu', en:'He will drive him', freq:1},
    {ar:'عَذَابًا', tr:'ʿadhāban', en:'into a punishment', freq:110},
    {ar:'صَعَدًا', tr:'ṣaʿadan', en:'overwhelming', freq:1},
  ]},
  {label:'72:18 — وَأَنَّ الْمَسَاجِدَ لِلَّهِ فَلَا تَدْعُوا مَعَ اللَّهِ أَحَدًا', words:[
    {ar:'وَأَنَّ', tr:'wa-anna', en:'And that', freq:76},
    {ar:'الْمَسَاجِدَ', tr:'al-masājida', en:'the mosques', freq:4},
    {ar:'لِلَّهِ', tr:'lillāhi', en:'are for Allah', freq:170},
    {ar:'فَلَا', tr:'fa-lā', en:'so do not', freq:100},
    {ar:'تَدْعُوا', tr:'tadʿū', en:'invoke', freq:10},
    {ar:'مَعَ', tr:'maʿa', en:'with', freq:55},
    {ar:'اللَّهِ', tr:'Allāhi', en:'Allah', freq:2699},
    {ar:'أَحَدًا', tr:'aḥadan', en:'anyone', freq:18},
  ]},
  {label:'72:19 — وَأَنَّهُ لَمَّا قَامَ عَبْدُ اللَّهِ يَدْعُوهُ كَادُوا يَكُونُونَ عَلَيْهِ لِبَدًا', words:[
    {ar:'وَأَنَّهُ', tr:'wa-annahu', en:'And that', freq:76},
    {ar:'لَمَّا', tr:'lammā', en:'when', freq:50},
    {ar:'قَامَ', tr:'qāma', en:'stood up', freq:7},
    {ar:'عَبْدُ', tr:'ʿabdu', en:'the servant of', freq:60},
    {ar:'اللَّهِ', tr:'Allāhi', en:'Allah', freq:2699},
    {ar:'يَدْعُوهُ', tr:'yadʿūhu', en:'calling upon Him', freq:4},
    {ar:'كَادُوا', tr:'kādū', en:'they almost', freq:5},
    {ar:'يَكُونُونَ', tr:'yakūnūna', en:'became', freq:18},
    {ar:'عَلَيْهِ', tr:'ʿalayhi', en:'upon him', freq:130},
    {ar:'لِبَدًا', tr:'libadan', en:'a compacted mass', freq:1},
  ]},
  {label:'72:20 — قُلْ إِنَّمَا أَدْعُو رَبِّي وَلَا أُشْرِكُ بِهِ أَحَدًا', words:[
    {ar:'قُلْ', tr:'qul', en:'Say', freq:332},
    {ar:'إِنَّمَا', tr:'innamā', en:'I only', freq:83},
    {ar:'أَدْعُو', tr:'adʿū', en:'invoke', freq:10},
    {ar:'رَبِّي', tr:'Rabbī', en:'my Lord', freq:40},
    {ar:'وَلَا', tr:'wa-lā', en:'and do not', freq:400},
    {ar:'أُشْرِكُ', tr:'ushriku', en:'associate', freq:4},
    {ar:'بِهِ', tr:'bihī', en:'with Him', freq:110},
    {ar:'أَحَدًا', tr:'aḥadan', en:'anyone', freq:18},
  ]},
  {label:'72:21 — قُلْ إِنِّي لَا أَمْلِكُ لَكُمْ ضَرًّا وَلَا رَشَدًا', words:[
    {ar:'قُلْ', tr:'qul', en:'Say', freq:332},
    {ar:'إِنِّي', tr:'innī', en:'indeed I', freq:107},
    {ar:'لَا', tr:'lā', en:'do not', freq:1738},
    {ar:'أَمْلِكُ', tr:'amliku', en:'possess', freq:4},
    {ar:'لَكُمْ', tr:'lakum', en:'for you', freq:183},
    {ar:'ضَرًّا', tr:'ḍarran', en:'any harm', freq:6},
    {ar:'وَلَا', tr:'wa-lā', en:'and not', freq:400},
    {ar:'رَشَدًا', tr:'rashadan', en:'right guidance', freq:3},
  ]},
  {label:'72:22 — قُلْ إِنِّي لَن يُجِيرَنِي مِنَ اللَّهِ أَحَدٌ وَلَنْ أَجِدَ مِن دُونِهِ مُلْتَحَدًا', words:[
    {ar:'قُلْ', tr:'qul', en:'Say', freq:332},
    {ar:'إِنِّي', tr:'innī', en:'indeed', freq:107},
    {ar:'لَن', tr:'lan', en:'never', freq:40},
    {ar:'يُجِيرَنِي', tr:'yujīranī', en:'can protect me', freq:1},
    {ar:'مِنَ', tr:'mina', en:'from', freq:3000},
    {ar:'اللَّهِ', tr:'Allāhi', en:'Allah', freq:2699},
    {ar:'أَحَدٌ', tr:'aḥadun', en:'anyone', freq:18},
    {ar:'وَلَنْ', tr:'wa-lan', en:'and never', freq:40},
    {ar:'أَجِدَ', tr:'ajida', en:'will I find', freq:16},
    {ar:'مِن', tr:'min', en:'besides', freq:3000},
    {ar:'دُونِهِ', tr:'dūnihī', en:'Him', freq:28},
    {ar:'مُلْتَحَدًا', tr:'multaḥadan', en:'a refuge', freq:1},
  ]},
  {label:'72:23 — إِلَّا بَلَاغًا مِّنَ اللَّهِ وَرِسَالَاتِهِ وَمَن يَعْصِ اللَّهَ وَرَسُولَهُ فَإِنَّ لَهُ نَارَ جَهَنَّمَ خَالِدِينَ فِيهَا أَبَدًا', words:[
    {ar:'إِلَّا', tr:'illā', en:'But only', freq:336},
    {ar:'بَلَاغًا', tr:'balāghan', en:'notification', freq:2},
    {ar:'مِّنَ', tr:'mina', en:'from', freq:3000},
    {ar:'اللَّهِ', tr:'Allāhi', en:'Allah', freq:2699},
    {ar:'وَرِسَالَاتِهِ', tr:'wa-risālātihī', en:'and His messages', freq:3},
    {ar:'وَمَن', tr:'wa-man', en:'and whoever', freq:540},
    {ar:'يَعْصِ', tr:'yaʿṣi', en:'disobeys', freq:4},
    {ar:'اللَّهَ', tr:'Allāha', en:'Allah', freq:2699},
    {ar:'وَرَسُولَهُ', tr:'wa-rasūlahu', en:'and His Messenger', freq:14},
    {ar:'فَإِنَّ', tr:'fa-inna', en:'then indeed', freq:490},
    {ar:'لَهُ', tr:'lahu', en:'for him', freq:220},
    {ar:'نَارَ', tr:'nāra', en:'is the fire of', freq:67},
    {ar:'جَهَنَّمَ', tr:'jahannama', en:'Hell', freq:55},
    {ar:'خَالِدِينَ', tr:'khālidīna', en:'abiding', freq:38},
    {ar:'فِيهَا', tr:'fīhā', en:'therein', freq:127},
    {ar:'أَبَدًا', tr:'abadan', en:'forever', freq:14},
  ]},
  {label:'72:24 — حَتَّىٰ إِذَا رَأَوْا مَا يُوعَدُونَ فَسَيَعْلَمُونَ مَنْ أَضْعَفُ نَاصِرًا وَأَقَلُّ عَدَدًا', words:[
    {ar:'حَتَّىٰ', tr:'ḥattā', en:'Until', freq:70},
    {ar:'إِذَا', tr:'idhā', en:'when', freq:362},
    {ar:'رَأَوْا', tr:'raʾaw', en:'they see', freq:20},
    {ar:'مَا', tr:'mā', en:'what', freq:2000},
    {ar:'يُوعَدُونَ', tr:'yūʿadūna', en:'they are promised', freq:8},
    {ar:'فَسَيَعْلَمُونَ', tr:'fa-sa-yaʿlamūna', en:'then they will know', freq:4},
    {ar:'مَنْ', tr:'man', en:'who is', freq:540},
    {ar:'أَضْعَفُ', tr:'aḍʿafu', en:'weaker', freq:2},
    {ar:'نَاصِرًا', tr:'nāṣiran', en:'in helper', freq:5},
    {ar:'وَأَقَلُّ', tr:'wa-aqallu', en:'and fewer', freq:3},
    {ar:'عَدَدًا', tr:'ʿadadan', en:'in number', freq:4},
  ]},
  {label:'72:25 — قُلْ إِنْ أَدْرِي أَقَرِيبٌ مَّا تُوعَدُونَ أَمْ يَجْعَلُ لَهُ رَبِّي أَمَدًا', words:[
    {ar:'قُلْ', tr:'qul', en:'Say', freq:332},
    {ar:'إِنْ', tr:'in', en:'not', freq:260},
    {ar:'أَدْرِي', tr:'adrī', en:'I know', freq:4},
    {ar:'أَقَرِيبٌ', tr:'a-qarībun', en:'whether near is', freq:3},
    {ar:'مَّا', tr:'mā', en:'what', freq:2000},
    {ar:'تُوعَدُونَ', tr:'tūʿadūna', en:'you are promised', freq:8},
    {ar:'أَمْ', tr:'am', en:'or', freq:120},
    {ar:'يَجْعَلُ', tr:'yajʿalu', en:'will set', freq:22},
    {ar:'لَهُ', tr:'lahu', en:'for it', freq:220},
    {ar:'رَبِّي', tr:'Rabbī', en:'my Lord', freq:40},
    {ar:'أَمَدًا', tr:'amadan', en:'a distant term', freq:2},
  ]},
  {label:'72:26 — عَالِمُ الْغَيْبِ فَلَا يُظْهِرُ عَلَىٰ غَيْبِهِ أَحَدًا', words:[
    {ar:'عَالِمُ', tr:'ʿālimu', en:'Knower of', freq:5},
    {ar:'الْغَيْبِ', tr:'al-ghaybi', en:'the unseen', freq:30},
    {ar:'فَلَا', tr:'fa-lā', en:'and He does not', freq:100},
    {ar:'يُظْهِرُ', tr:'yuẓhiru', en:'reveal', freq:2},
    {ar:'عَلَىٰ', tr:'ʿalā', en:'over', freq:820},
    {ar:'غَيْبِهِ', tr:'ghaybihī', en:'His unseen', freq:6},
    {ar:'أَحَدًا', tr:'aḥadan', en:'anyone', freq:18},
  ]},
  {label:'72:27 — إِلَّا مَنِ ارْتَضَىٰ مِن رَّسُولٍ فَإِنَّهُ يَسْلُكُ مِن بَيْنِ يَدَيْهِ وَمِنْ خَلْفِهِ رَصَدًا', words:[
    {ar:'إِلَّا', tr:'illā', en:'Except', freq:336},
    {ar:'مَنِ', tr:'mani', en:'whom', freq:540},
    {ar:'ارْتَضَىٰ', tr:'irtaḍā', en:'He has approved', freq:3},
    {ar:'مِن', tr:'min', en:'of', freq:3000},
    {ar:'رَّسُولٍ', tr:'rasūlin', en:'a messenger', freq:75},
    {ar:'فَإِنَّهُ', tr:'fa-innahu', en:'then He', freq:76},
    {ar:'يَسْلُكُ', tr:'yasluku', en:'sends', freq:3},
    {ar:'مِن', tr:'min', en:'before', freq:3000},
    {ar:'بَيْنِ', tr:'bayni', en:'before him', freq:120},
    {ar:'يَدَيْهِ', tr:'yadayhi', en:'his hands', freq:16},
    {ar:'وَمِنْ', tr:'wa-min', en:'and behind', freq:3000},
    {ar:'خَلْفِهِ', tr:'khalfihī', en:'him', freq:5},
    {ar:'رَصَدًا', tr:'raṣadan', en:'observers', freq:2},
  ]},
  {label:'72:28 — لِّيَعْلَمَ أَن قَدْ أَبْلَغُوا رِسَالَاتِ رَبِّهِمْ وَأَحَاطَ بِمَا لَدَيْهِمْ وَأَحْصَىٰ كُلَّ شَيْءٍ عَدَدًا', words:[
    {ar:'لِّيَعْلَمَ', tr:'li-yaʿlama', en:'That He may know', freq:14},
    {ar:'أَن', tr:'an', en:'that', freq:560},
    {ar:'قَدْ', tr:'qad', en:'indeed', freq:200},
    {ar:'أَبْلَغُوا', tr:'ablaghū', en:'they have conveyed', freq:1},
    {ar:'رِسَالَاتِ', tr:'risālāti', en:'the messages', freq:3},
    {ar:'رَبِّهِمْ', tr:'Rabbihim', en:'of their Lord', freq:36},
    {ar:'وَأَحَاطَ', tr:'wa-aḥāṭa', en:'and He has encompassed', freq:4},
    {ar:'بِمَا', tr:'bi-mā', en:'whatever', freq:80},
    {ar:'لَدَيْهِمْ', tr:'ladayhim', en:'is with them', freq:6},
    {ar:'وَأَحْصَىٰ', tr:'wa-aḥṣā', en:'and has enumerated', freq:2},
    {ar:'كُلَّ', tr:'kulla', en:'every', freq:182},
    {ar:'شَيْءٍ', tr:'shayʾin', en:'thing', freq:200},
    {ar:'عَدَدًا', tr:'ʿadadan', en:'in number', freq:4},
  ]},
];
window.setupWBWLevel(WBW_DATA, 10);
