'use strict';
/* scenes.js */
const CW=560,CH=220,P=4;
function _lbl(ctx,t,c,y){ctx.fillStyle=c||'#ffffff';ctx.font='6px "Press Start 2P",monospace';ctx.textAlign='center';ctx.fillText(t,CW/2,y||15);ctx.textAlign='left';}
function _fig(ctx,x,y,hc,bc,pc,r){const S=document.documentElement.getAttribute('data-theme')==='stars';ctx.fillStyle=hc;if(S&&r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x+P,y,P*3,P*3,2);else ctx.rect(x+P,y,P*3,P*3);ctx.fill();}else ctx.fillRect(x+P,y,P*3,P*3);ctx.fillStyle=bc;ctx.fillRect(x,y+P*3,P*5,P*4);ctx.fillStyle=pc;ctx.fillRect(x,y+P*7,P*2,P*4);ctx.fillRect(x+P*3,y+P*7,P*2,P*4);}
class BS{constructor(id){this.canvas=document.getElementById(id);this.ctx=this.canvas?this.canvas.getContext('2d'):null;this.raf=null;this.t=0;}stop(){if(this.raf){cancelAnimationFrame(this.raf);this.raf=null;}}}
const VD_s1={ref:'An-Nasr 110:1',arabic:'إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ',english:'"When Allah\'s help and the conquest comes." (110:1)',note:'Conquest of Mecca. 8 AH. The turning point.'};
const VD_s2={ref:'An-Nasr 110:2',arabic:'يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا',english:'"People entering the religion in crowds." (110:2)',note:'Afwaja — masses! After years of small numbers.'};
const VD_s3={ref:'An-Nasr 110:3',arabic:'فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ',english:'"Glorify your Lord and seek forgiveness." (110:3)',note:'Victory answered with tasbih and istighfar. Humility.'};
class S1 extends BS{constructor(){super('canvas-1');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s1);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#060e08';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#162818';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('🏆',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#80e090';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('إِذَا جَاءَ نَصْرُ اللَّهِ و',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"When Allah\'s help and the conquest comes." (110:1)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Victory Arrives — 110:1','#e8fff0');};draw();}}
class S2 extends BS{constructor(){super('canvas-2');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s2);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#060e08';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#162818';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('👥',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#80e090';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('يَدْخُلُونَ فِي دِينِ اللَّه',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"People entering the religion in crowds." (110:2)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Masses Enter Islam — 110:2','#e8fff0');};draw();}}
class S3 extends BS{constructor(){super('canvas-3');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s3);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#060e08';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#162818';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('🤲',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#80e090';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('فَسَبِّحْ بِحَمْدِ رَبِّكَ و',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"Glorify your Lord and seek forgiveness." (110:3)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Glorify and Forgive — 110:3','#e8fff0');};draw();}}
const scenes={};
function initScenes(){scenes[1]=new S1();scenes[2]=new S2();scenes[3]=new S3();}
function startScene(n){if(scenes[n])scenes[n].start();}
function stopAllScenes(){Object.values(scenes).forEach(s=>s.stop());}
