'use strict';
/* scenes.js */
const CW=560,CH=220,P=4;
function _lbl(ctx,t,c,y){ctx.fillStyle=c||'#ffffff';ctx.font='6px "Press Start 2P",monospace';ctx.textAlign='center';ctx.fillText(t,CW/2,y||15);ctx.textAlign='left';}
function _fig(ctx,x,y,hc,bc,pc,r){const S=document.documentElement.getAttribute('data-theme')==='stars';ctx.fillStyle=hc;if(S&&r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x+P,y,P*3,P*3,2);else ctx.rect(x+P,y,P*3,P*3);ctx.fill();}else ctx.fillRect(x+P,y,P*3,P*3);ctx.fillStyle=bc;ctx.fillRect(x,y+P*3,P*5,P*4);ctx.fillStyle=pc;ctx.fillRect(x,y+P*7,P*2,P*4);ctx.fillRect(x+P*3,y+P*7,P*2,P*4);}
class BS{constructor(id){this.canvas=document.getElementById(id);this.ctx=this.canvas?this.canvas.getContext('2d'):null;this.raf=null;this.t=0;}stop(){if(this.raf){cancelAnimationFrame(this.raf);this.raf=null;}}}
const VD_time={ref:'Al-Asr 103:1-2',arabic:'وَالْعَصْرِ ۩ إِنَّ الْإِنسَانَ لَفِي خُسْرٍ',english:'"By time! Mankind is in loss." (103:1-2)',note:"Imam Shafi'i said this surah alone is sufficient if truly understood."};
const VD_four={ref:'Al-Asr 103:3',arabic:'إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ',english:'"Except those who believe and do righteous deeds..." (103:3)',note:'Four conditions: iman, deeds, urge to truth, urge to patience. All four required.'};
const VD_comm={ref:'Al-Asr 103:3',arabic:'وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ',english:'"Urge each other to truth and to patience." (103:3)',note:'Community mutual obligation. Tawasi = communal urging. Both truth AND patience.'};
class S1 extends BS{constructor(){super('canvas-1');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_time);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#1e0e02';ctx.fillRect(0,0,CW,CH);ctx.strokeStyle='rgba(248,192,80,0.6)';ctx.lineWidth=2;ctx.strokeRect(CW/2-15,CH*0.25,30,50);ctx.beginPath();ctx.moveTo(CW/2-15,CH*0.25);ctx.lineTo(CW/2+15,CH*0.5);ctx.lineTo(CW/2-15,CH*0.75);ctx.lineTo(CW/2+15,CH*0.25);ctx.lineTo(CW/2-15,CH*0.25);ctx.stroke();ctx.fillStyle='rgba(248,192,80,0.8)';ctx.beginPath();ctx.moveTo(CW/2-14,CH*0.51);ctx.lineTo(CW/2+14,CH*0.51);ctx.lineTo(CW/2,CH*0.74);ctx.fill();ctx.fillStyle='#f8c050';ctx.font='5px "Press Start 2P",monospace';ctx.textAlign='center';ctx.fillText('Time runs! Mankind is in LOSS! (103:1-2)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: By Time — 103:1-2','#fff8e0');};draw();}}
class S2 extends BS{constructor(){super('canvas-2');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_four);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#1e0e02';ctx.fillRect(0,0,CW,CH);const items=[['Iman','💛'],['Amal','⭐'],['Haqq','📖'],['Sabr','🤲']];items.forEach(([t,e],i)=>{ctx.font='16px serif';ctx.textAlign='center';ctx.fillText(e,80+i*130,CH*0.5);ctx.fillStyle='#f8c050';ctx.font='5px "Press Start 2P",monospace';ctx.fillText(t,80+i*130,CH*0.65);ctx.textAlign='left';});_lbl(ctx,'CLICK: Four Conditions — 103:3','#fff8e0');};draw();}}
class S3 extends BS{constructor(){super('canvas-3');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_comm);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#1e0e02';ctx.fillRect(0,0,CW,CH);_fig(ctx,140,100,'#e8c090','#204080','#102060',true);_fig(ctx,240,100,'#f0d0a0','#601040','#400828',true);_fig(ctx,340,100,'#d8b870','#203a60','#101e40',true);ctx.strokeStyle='rgba(248,192,80,0.4)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(170,128);ctx.lineTo(240,128);ctx.lineTo(360,128);ctx.stroke();ctx.fillStyle='#f8c050';ctx.font='5px "Press Start 2P",monospace';ctx.textAlign='center';ctx.fillText('TRUTH + PATIENCE — communal duty! (103:3)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Community Duty — 103:3','#fff8e0');};draw();}}
const scenes={};
function initScenes(){scenes[1]=new S1();scenes[2]=new S2();scenes[3]=new S3();}
function startScene(n){if(scenes[n])scenes[n].start();}
function stopAllScenes(){Object.values(scenes).forEach(s=>s.stop());}
