'use strict';
/* scenes.js */
const CW=560,CH=220,P=4;
function _lbl(ctx,t,c,y){ctx.fillStyle=c||'#ffffff';ctx.font='6px "Press Start 2P",monospace';ctx.textAlign='center';ctx.fillText(t,CW/2,y||15);ctx.textAlign='left';}
function _fig(ctx,x,y,hc,bc,pc,r){const S=document.documentElement.getAttribute('data-theme')==='stars';ctx.fillStyle=hc;if(S&&r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x+P,y,P*3,P*3,2);else ctx.rect(x+P,y,P*3,P*3);ctx.fill();}else ctx.fillRect(x+P,y,P*3,P*3);ctx.fillStyle=bc;ctx.fillRect(x,y+P*3,P*5,P*4);ctx.fillStyle=pc;ctx.fillRect(x,y+P*7,P*2,P*4);ctx.fillRect(x+P*3,y+P*7,P*2,P*4);}
class BS{constructor(id){this.canvas=document.getElementById(id);this.ctx=this.canvas?this.canvas.getContext('2d'):null;this.raf=null;this.t=0;}stop(){if(this.raf){cancelAnimationFrame(this.raf);this.raf=null;}}}
const VD_iqra={ref:'Al-Alaq 96:1',arabic:'اقْرَأْ بِاسْمِ رَبِّكَ',english:'"Read in the name of your Lord." (96:1)',note:'First word of revelation. Knowledge is sacred when tied to Allah.'};
const VD_clot={ref:'Al-Alaq 96:2',arabic:'خَلَقَ الْإِنسَانَ مِنْ عَلَقٍ',english:'"Created man from a clinging clot." (96:2)',note:'Humble origin, divine honour through the pen and knowledge.'};
const VD_tyrant={ref:'Al-Alaq 96:6-7',arabic:'كَلَّا إِنَّ الْإِنسَانَ لَيَطْغَىٰ',english:'"Man transgresses when he sees himself as self-sufficient." (96:6-7)',note:'Istagna — the root of all transgression. Abu Jahl threatened the Prophet ﷺ.'};
const VD_story={ref:'Al-Alaq 96:9-14',arabic:'أَرَأَيْتَ الَّذِي يَنْهَىٰ عَبْدًا إِذَا صَلَّىٰ',english:'"Have you seen him who forbids a servant when he prays?" (96:9-10)',note:"Abu Jahl threatened to step on the Prophet's neck. Allah warned: seize by the forelock."};
const VD_sajdah={ref:'Al-Alaq 96:19',arabic:'وَاسْجُدْ وَاقْتَرِبْ',english:'"Prostrate and draw near to Allah." (96:19)',note:'The closest a servant gets to Allah is in sujud. This verse has a sajdah tilawah.'};
class S2 extends BS{constructor(){super('canvas-2');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_iqra);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#1a0404';ctx.fillRect(0,0,CW,CH);const glow=0.2+Math.sin(this.t*0.04)*0.1;const rg=ctx.createRadialGradient(CW/2,CH*0.5,5,CW/2,CH*0.5,80);rg.addColorStop(0,`rgba(240,96,64,${glow})`);rg.addColorStop(1,'transparent');ctx.fillStyle=rg;ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#f06040';ctx.font='22px serif';ctx.textAlign='center';ctx.fillText('اقْرَأْ',CW/2,CH*0.5);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"READ!" — First word revealed',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Iqra! — 96:1','#fff0e8');};draw();}}
class S3 extends BS{constructor(){super('canvas-3');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_clot);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#1a0404';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#f06040';ctx.font='22px serif';ctx.textAlign='center';ctx.fillText('🩸',CW/2,CH*0.45);ctx.font='8px serif';ctx.fillText('عَلَق',CW/2,CH*0.65);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('Created from clot — given the pen and knowledge',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: The Clot — 96:2','#fff0e8');};draw();}}
class S4 extends BS{constructor(){super('canvas-4');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_tyrant);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#1a0404';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='rgba(200,40,20,0.2)';ctx.fillRect(0,0,CW,CH);_fig(ctx,150,100,'#b09060','#502010','#380808',false);ctx.fillStyle='#f06040';ctx.font='8px serif';ctx.textAlign='center';ctx.fillText('اسْتَغْنَىٰ',CW/2,CH*0.3);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('Self-sufficiency leads to transgression (96:6-7)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Transgression — 96:6-7','#fff0e8');};draw();}}
class S5 extends BS{constructor(){super('canvas-5');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_story);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#1a0404';ctx.fillRect(0,0,CW,CH);_fig(ctx,CW/2-10,100,'#f0d090','#204080','#102060',true);ctx.fillStyle='rgba(255,80,40,0.3)';ctx.fillRect(CW*0.6,80,90,80);ctx.fillStyle='#f06040';ctx.font='5px "Press Start 2P",monospace';ctx.textAlign='center';ctx.fillText('Prophet prays. Enemy threatens. Allah warns!',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Abu Jahl Threatens — 96:9-14','#fff0e8');};draw();}}
class S6 extends BS{constructor(){super('canvas-6');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_sajdah);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#1a0404';ctx.fillRect(0,0,CW,CH);const glow=0.2+Math.sin(this.t*0.04)*0.1;const rg=ctx.createRadialGradient(CW/2,CH*0.55,5,CW/2,CH*0.55,60);rg.addColorStop(0,`rgba(240,96,64,${glow})`);rg.addColorStop(1,'transparent');ctx.fillStyle=rg;ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#f06040';ctx.font='9px serif';ctx.textAlign='center';ctx.fillText('وَاسْجُدْ وَاقْتَرِبْ',CW/2,CH*0.45);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"Prostrate and DRAW NEAR!" — 96:19',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Prostrate and Draw Near — 96:19','#fff0e8');};draw();}}
const scenes={};




const VD_wbw={ref:'Al-Alaq (96)',arabic:'اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ ۩ خَلَقَ الْإِنسَانَ مِنْ عَلَقٍ ۩ اقْرَأْ وَرَبُّكَ الْأَكْرَمُ ۩ الَّذِي عَلَّمَ بِالْقَلَمِ',english:'"Read in the name of your Lord who created — created man from a clinging clot. Read, and your Lord is the Most Generous — who taught by the pen." (96:1-4)',note:'Key Arabic words from this surah. Tap each flip card below to learn them one by one.'};
const _s1wbw = new window.WBWScene('canvas-1', {emoji:'📖',label:'THE CLOT — READ!',verse:VD_wbw});

function initScenes(){scenes[1]=_s1wbw;scenes[2]=new S2();scenes[3]=new S3();scenes[4]=new S4();scenes[5]=new S5();scenes[6]=new S6();}
function startScene(n) {
  if(scenes[n])scenes[n].start();}
function stopAllScenes() {
  Object.values(scenes).forEach(s=>s.stop());}
