'use strict';
/* scenes.js */
const CW=560,CH=220,P=4;
function _lbl(ctx,t,c,y){ctx.fillStyle=c||'#ffffff';ctx.font='6px "Press Start 2P",monospace';ctx.textAlign='center';ctx.fillText(t,CW/2,y||15);ctx.textAlign='left';}
function _fig(ctx,x,y,hc,bc,pc,r){const S=document.documentElement.getAttribute('data-theme')==='stars';ctx.fillStyle=hc;if(S&&r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x+P,y,P*3,P*3,2);else ctx.rect(x+P,y,P*3,P*3);ctx.fill();}else ctx.fillRect(x+P,y,P*3,P*3);ctx.fillStyle=bc;ctx.fillRect(x,y+P*3,P*5,P*4);ctx.fillStyle=pc;ctx.fillRect(x,y+P*7,P*2,P*4);ctx.fillRect(x+P*3,y+P*7,P*2,P*4);}
class BS{constructor(id){this.canvas=document.getElementById(id);this.ctx=this.canvas?this.canvas.getContext('2d'):null;this.raf=null;this.t=0;}stop(){if(this.raf){cancelAnimationFrame(this.raf);this.raf=null;}}}
const VD_open={ref:'Ash-Sharh 94:1-4',arabic:'أَلَمْ نَشْرَحْ لَكَ صَدْرَكَ',english:'"Did We not expand your chest?" (94:1)',note:'Expansion of the chest = spiritual capacity. Burden removed. Mention raised worldwide.'};
const VD_ease={ref:'Ash-Sharh 94:5-6',arabic:'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا',english:'"With hardship comes ease." (94:5)',note:"Twice said. With (ma'a) not after. The same hardship brings two different eases."};
const VD_strive={ref:'Ash-Sharh 94:7-8',arabic:'فَإِذَا فَرَغْتَ فَانصَبْ',english:'"When you are free, strive again!" (94:7)',note:'No permanent rest — when done, begin the next striving. Turn to Allah with yearning.'};
class S1 extends BS{constructor(){super('canvas-1');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_open);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#061820';ctx.fillRect(0,0,CW,CH);const glow=0.15+Math.sin(this.t*0.04)*0.08;const rg=ctx.createRadialGradient(CW/2,CH*0.45,8,CW/2,CH*0.45,70);rg.addColorStop(0,`rgba(64,216,192,${glow*3})`);rg.addColorStop(1,'transparent');ctx.fillStyle=rg;ctx.fillRect(0,0,CW,CH);_fig(ctx,CW/2-10,100,'#f0d090','#204080','#102060',true);ctx.fillStyle='#40d8c0';ctx.font='8px serif';ctx.textAlign='center';ctx.fillText('💙',CW/2,88);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('Expanded chest, burden removed, name raised! (94:1-4)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Expanded Chest — 94:1-4','#e0f8ff');};draw();}}
class S2 extends BS{constructor(){super('canvas-2');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_ease);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#061820';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='rgba(64,216,192,0.15)';ctx.fillRect(CW/2,0,CW/2,CH);ctx.fillStyle='#40d8c0';ctx.font='10px serif';ctx.textAlign='center';ctx.fillText('مَعَ الْعُسْرِ يُسْرًا',CW/2,CH*0.35);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"WITH hardship comes ease" — twice said! (94:5-6)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Ease With Hardship — 94:5-6','#e0f8ff');};draw();}}
class S3 extends BS{constructor(){super('canvas-3');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_strive);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#061820';ctx.fillRect(0,0,CW,CH);for(let i=0;i<5;i++){const ap=0.3+Math.sin(this.t*0.04+i)*0.2;ctx.strokeStyle=`rgba(64,216,192,${ap})`;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(100+i*80,CH*0.7);ctx.lineTo(140+i*80,CH*0.3);ctx.stroke();}ctx.fillStyle='#40d8c0';ctx.font='5px "Press Start 2P",monospace';ctx.textAlign='center';ctx.fillText('"When free, STRIVE AGAIN — turn to your Lord!" (94:7-8)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Strive Again — 94:7-8','#e0f8ff');};draw();}}
const scenes={};
function initScenes(){scenes[1]=new S1();scenes[2]=new S2();scenes[3]=new S3();}
function startScene(n){if(scenes[n])scenes[n].start();}
function stopAllScenes(){Object.values(scenes).forEach(s=>s.stop());}
