'use strict';
/* scenes.js */
const CW=560,CH=220,P=4;
function _lbl(ctx,t,c,y){ctx.fillStyle=c||'#ffffff';ctx.font='6px "Press Start 2P",monospace';ctx.textAlign='center';ctx.fillText(t,CW/2,y||15);ctx.textAlign='left';}
function _fig(ctx,x,y,hc,bc,pc,r){const S=document.documentElement.getAttribute('data-theme')==='stars';ctx.fillStyle=hc;if(S&&r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x+P,y,P*3,P*3,2);else ctx.rect(x+P,y,P*3,P*3);ctx.fill();}else ctx.fillRect(x+P,y,P*3,P*3);ctx.fillStyle=bc;ctx.fillRect(x,y+P*3,P*5,P*4);ctx.fillStyle=pc;ctx.fillRect(x,y+P*7,P*2,P*4);ctx.fillRect(x+P*3,y+P*7,P*2,P*4);}
class BS{constructor(id){this.canvas=document.getElementById(id);this.ctx=this.canvas?this.canvas.getContext('2d'):null;this.raf=null;this.t=0;}stop(){if(this.raf){cancelAnimationFrame(this.raf);this.raf=null;}}}
const VD_s1={ref:'Al-Fil 105:1',arabic:'أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ',english:'"Did you not see how your Lord dealt..." (105:1)',note:'Abraha: 60,000 soldiers + 13 elephants to destroy the Kaaba.'};
const VD_s2={ref:'Al-Fil 105:3-4',arabic:'وَأَرْسَلَ عَلَيْهِمْ طَيْرًا أَبَابِيلَ',english:'"He sent against them birds in flocks." (105:3)',note:'Birds carrying sijjil stones. Allah needs no army.'};
const VD_s3={ref:'Al-Fil 105:5',arabic:'فَجَعَلَهُمْ كَعَصْفٍ مَّأْكُولٍ',english:'"He made them like eaten straw." (105:5)',note:'60,000 soldiers reduced to nothing. Mecca protected.'};
class S1 extends BS{constructor(){super('canvas-1');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s1);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#101418';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#202a30';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('🐘',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#a0b8d0';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('أَلَمْ تَرَ كَيْفَ فَعَلَ رَ',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"Did you not see how your Lord dealt..." (105:1)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Army of Elephant — 105:1','#f0f4ff');};draw();}}
class S2 extends BS{constructor(){super('canvas-2');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s2);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#101418';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#202a30';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('🐦',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#a0b8d0';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('وَأَرْسَلَ عَلَيْهِمْ طَيْرً',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"He sent against them birds in flocks." (105:3)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Birds of Ababil — 105:3-4','#f0f4ff');};draw();}}
class S3 extends BS{constructor(){super('canvas-3');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s3);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#101418';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#202a30';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('🌾',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#a0b8d0';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('فَجَعَلَهُمْ كَعَصْفٍ مَّأْك',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"He made them like eaten straw." (105:5)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Like Eaten Straw — 105:5','#f0f4ff');};draw();}}
const scenes={};
function initScenes(){scenes[1]=new S1();scenes[2]=new S2();scenes[3]=new S3();}
function startScene(n){if(scenes[n])scenes[n].start();}
function stopAllScenes(){Object.values(scenes).forEach(s=>s.stop());}
