'use strict';
/* scenes.js */
const CW=560,CH=220,P=4;
function _lbl(ctx,t,c,y){ctx.fillStyle=c||'#ffffff';ctx.font='6px "Press Start 2P",monospace';ctx.textAlign='center';ctx.fillText(t,CW/2,y||15);ctx.textAlign='left';}
function _fig(ctx,x,y,hc,bc,pc,r){const S=document.documentElement.getAttribute('data-theme')==='stars';ctx.fillStyle=hc;if(S&&r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x+P,y,P*3,P*3,2);else ctx.rect(x+P,y,P*3,P*3);ctx.fill();}else ctx.fillRect(x+P,y,P*3,P*3);ctx.fillStyle=bc;ctx.fillRect(x,y+P*3,P*5,P*4);ctx.fillStyle=pc;ctx.fillRect(x,y+P*7,P*2,P*4);ctx.fillRect(x+P*3,y+P*7,P*2,P*4);}
class BS{constructor(id){this.canvas=document.getElementById(id);this.ctx=this.canvas?this.canvas.getContext('2d'):null;this.raf=null;this.t=0;}stop(){if(this.raf){cancelAnimationFrame(this.raf);this.raf=null;}}}
const VD_s1={ref:'Al-Falaq 113:1',arabic:'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ',english:'"Seek refuge in the Lord of the Daybreak." (113:1)',note:'Lord who commands morning to break through darkness.'};
const VD_s2={ref:'Al-Falaq 113:2-4',arabic:'مِن شَرِّ مَا خَلَقَ ۩ وَمِن شَرِّ غَاسِقٍ',english:'"From evil of creation, of darkening night..." (113:2-3)',note:'Four evils: creation, night, witchcraft, envy.'};
const VD_s3={ref:'Al-Falaq 113:4-5',arabic:'وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',english:'"From evil of an envier when they envy." (113:5)',note:"Al-Mu'awwidhatayn. Seek refuge morning and evening."};
class S1 extends BS{constructor(){super('canvas-1');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s1);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#100828';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#281850';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('🌅',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#e0a0f0';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('قُلْ أَعُوذُ بِرَبِّ الْفَلَ',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"Seek refuge in the Lord of the Daybreak." (113:1)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Lord of Daybreak — 113:1','#fff0ff');};draw();}}
class S2 extends BS{constructor(){super('canvas-2');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s2);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#100828';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#281850';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('🌑',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#e0a0f0';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('مِن شَرِّ مَا خَلَقَ ۩ وَمِن',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"From evil of creation, of darkening night..." (113:2-3)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Four Evils — 113:2-5','#fff0ff');};draw();}}
class S3 extends BS{constructor(){super('canvas-3');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s3);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#100828';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#281850';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('🔮',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#e0a0f0';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('وَمِن شَرِّ حَاسِدٍ إِذَا حَ',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"From evil of an envier when they envy." (113:5)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: The Envier — 113:5','#fff0ff');};draw();}}
const scenes={};
function initScenes(){scenes[1]=new S1();scenes[2]=new S2();scenes[3]=new S3();}
function startScene(n){if(scenes[n])scenes[n].start();}
function stopAllScenes(){Object.values(scenes).forEach(s=>s.stop());}
