'use strict';
/* scenes.js */
const CW=560,CH=220,P=4;
function _lbl(ctx,t,c,y){ctx.fillStyle=c||'#ffffff';ctx.font='6px "Press Start 2P",monospace';ctx.textAlign='center';ctx.fillText(t,CW/2,y||15);ctx.textAlign='left';}
function _fig(ctx,x,y,hc,bc,pc,r){const S=document.documentElement.getAttribute('data-theme')==='stars';ctx.fillStyle=hc;if(S&&r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x+P,y,P*3,P*3,2);else ctx.rect(x+P,y,P*3,P*3);ctx.fill();}else ctx.fillRect(x+P,y,P*3,P*3);ctx.fillStyle=bc;ctx.fillRect(x,y+P*3,P*5,P*4);ctx.fillStyle=pc;ctx.fillRect(x,y+P*7,P*2,P*4);ctx.fillRect(x+P*3,y+P*7,P*2,P*4);}
class BS{constructor(id){this.canvas=document.getElementById(id);this.ctx=this.canvas?this.canvas.getContext('2d'):null;this.raf=null;this.t=0;}stop(){if(this.raf){cancelAnimationFrame(this.raf);this.raf=null;}}}
const VD_s1={ref:'Al-Qaria 101:1-3',arabic:'الْقَارِعَةُ ۩ مَا الْقَارِعَةُ',english:'"The Striking Hour! What is it?" (101:1-2)',note:'Three times for dread. Moths. Wool mountains.'};
const VD_s2={ref:'Al-Qaria 101:4-5',arabic:'يَوْمَ يَكُونُ النَّاسُ كَالْفَرَاشِ الْمَبْثُوثِ',english:'"People like scattered moths." (101:4)',note:'Overwhelmed, helpless. Mountains become wool.'};
const VD_s3={ref:'Al-Qaria 101:6-11',arabic:'فَأَمَّا مَن ثَقُلَتْ مَوَازِينُهُ',english:'"Heavy scales: a pleasant life." (101:6-7)',note:'Heavy = Jannah. Light = Hawiyah (blazing abyss).'};
class S1 extends BS{constructor(){super('canvas-1');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s1);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#1a0408';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#381018';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('💥',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#f86050';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('الْقَارِعَةُ ۩ مَا الْقَارِع',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"The Striking Hour! What is it?" (101:1-2)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: The Striking Hour — 101:1-3','#fff0f0');};draw();}}
class S2 extends BS{constructor(){super('canvas-2');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s2);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#1a0408';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#381018';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('🦋',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#f86050';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('يَوْمَ يَكُونُ النَّاسُ كَال',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"People like scattered moths." (101:4)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: Scattered Moths — 101:4-5','#fff0f0');};draw();}}
class S3 extends BS{constructor(){super('canvas-3');}start(){if(!this.ctx)return;this.canvas.onclick=()=>showVersePopup(VD_s3);const ctx=this.ctx;const draw=()=>{this.t++;this.raf=requestAnimationFrame(draw);ctx.fillStyle='#1a0408';ctx.fillRect(0,0,CW,CH);ctx.fillStyle='#381018';ctx.fillRect(0,CH*0.65,CW,CH*0.35);ctx.font='26px serif';ctx.textAlign='center';ctx.fillText('⚖️',CW/2,CH*0.5);ctx.textAlign='left';ctx.fillStyle='#f86050';ctx.font='7px serif';ctx.textAlign='center';ctx.fillText('فَأَمَّا مَن ثَقُلَتْ مَوَاز',CW/2,CH*0.28);ctx.font='5px "Press Start 2P",monospace';ctx.fillText('"Heavy scales: a pleasant life." (101:6-7)',CW/2,CH-8);ctx.textAlign='left';_lbl(ctx,'CLICK: The Scales — 101:6-11','#fff0f0');};draw();}}
const scenes={};
function initScenes(){scenes[1]=new S1();scenes[2]=new S2();scenes[3]=new S3();}
function startScene(n){if(scenes[n])scenes[n].start();}
function stopAllScenes(){Object.values(scenes).forEach(s=>s.stop());}
